# Site settings
baseurl = "http://malcantara.github.io/"
languageCode = "en-us"
title = "Mario Alcantara Galindo"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    author = "Mario Alcantara"
    name = "Mario Alcantara Galindo"
    description = "Mario's personal website."

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "marioag49@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Mario Alcantara Galindo"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "logo-mario-small.png"
        name = "Mario Alcantara Galindo"
        subtitle = "Programmer - Traveller - Learner"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Background"

        [params.portfolio.modal]
            client = "Client"
            date = "Experience"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About me"
        # The about text is splitted into a left and right column
        left = "I am a computer programmer specialized in web and mobile development. Full stack web developer who enjoys working with backend stuff."
        right = "Besides software development I like travelling, enjoying the nature's beauty and reading about History."



    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "All rights reserved."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Toluca, Estado de México.", "México."]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                text = "LinkedIn"
                icon = "fa-linkedin"
                link = "//linkedin.com/in/mario-alcantara-galindo-b2271b29"

        [params.footer.credits]
            text = "Powerede by [Hugo](//hugo.io) and [Freelance Theme](//themes.gohugo.io/theme/freelancer/). [Kamaleon](//kameleon.pics) icons."
